application: somwut-j
version: 1
runtime: go
api_version: go1

handlers:
- url: /rest/channel/.*
  script: _go_app
  login: required
- url: /rest/portfolio/.*
  script: _go_app
- url: /rest/dict/.*
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /dict
  static_files: static/dict.html
  upload: static/dict.html
- url: /channel
  static_files: static/channel.html
  upload: static/channel.html
- url: /
  static_dir: static